### ISSUE TITLE
Contact form 7 support

### ISSUE THREAD

**Issue by timscha** [post-duif/integration-listmonk-wordpress-plugin#22] opened 2024-02-18 06:16 UTC
Hello,
I just came across your plugin which I would really like to use. :)

Unfortunately the theme I am using is only compatible with contact form 7 (https://wordpress.org/plugins/contact-form-7/)
Is there any chance that an integration is planned here at some point?

Thank you in advance
Tim

**Comment by timscha** [comment] 2024-02-18 06:30
Oh and I got the following error when opening the settings page:

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.4.3
Current plugin: Integration for listmonk mailing list and newsletter manager (version 1.2.0)
PHP version 8.3.2-1+0~20240120.16+debian12~1.gbpb43448

Error Details
=============
An error of type E_ERROR was caused in line 21 of the file /var/www/vhosts/[staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php](http://staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php). Error message: Uncaught Error: Call to undefined function wc_get_page_id() in /var/www/vhosts/[staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php:21](http://staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php:21)
Stack trace:
#0 /var/www/vhosts/[staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php](http://staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php)(379): listmonk_is_checkout_block_enabled()
#1 /var/www/vhosts/[staging.example.com/public/wp-includes/class-wp-hook.php](http://staging.example.com/public/wp-includes/class-wp-hook.php)(324): listmonk_integration_page_callback()
#2 /var/www/vhosts/[staging.example.com/public/wp-includes/class-wp-hook.php](http://staging.example.com/public/wp-includes/class-wp-hook.php)(348): WP_Hook->apply_filters()
#3 /var/www/vhosts/[staging.example.com/public/wp-includes/plugin.php](http://staging.example.com/public/wp-includes/plugin.php)(517): WP_Hook->do_action()
#4 /var/www/vhosts/[staging.example.com/public/wp-admin/admin.php](http://staging.example.com/public/wp-admin/admin.php)(259): do_action()
#5 /var/www/vhosts/[staging.example.com/public/wp-admin/options-general.php](http://staging.example.com/public/wp-admin/options-general.php)(10): require_once('...')
#6 {main}
 thrown

**Comment by post-duif** [comment] 2024-02-18 07:52
Hey Tim, I will check it out! Do you know if Contact form 7 supports developers with custom hooks?

And regarding the error, what version of WordPress are you on? And do you use WooCommerce?

**Comment by timscha** [comment] 2024-02-18 08:14
Hi @post-duif Thanks for your fast response.
Regarding hooks, I don't know, I only found about that one: https://wpdebuglog.com/forums/topic/hooks-list-contact-form-7/

I am not using WooCommerce. Using the latest WP versipn 6.4.3 with PHP 8.3, nginx and MariaDB 10.11.

**Comment by post-duif** [comment] 2024-02-23 17:38
> Oh and I got the following error when opening the settings page:
> 
> When seeking help with this issue, you may be asked for some of the following information:
> WordPress version 6.4.3
> Current plugin: Integration for listmonk mailing list and newsletter manager (version 1.2.0)
> PHP version 8.3.2-1+0~20240120.16+debian12~1.gbpb43448
> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 21 of the file /var/www/vhosts/[staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php](http://staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php). Error message: Uncaught Error: Call to undefined function wc_get_page_id() in /var/www/vhosts/[staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php:21](http://staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php:21)
> Stack trace:
> #0 /var/www/vhosts/[staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php](http://staging.example.com/public/wp-content/plugins/integration-listmonk-wordpress-plugin-1.2.1/listmonk-integration.php)(379): listmonk_is_checkout_block_enabled()
> #1 /var/www/vhosts/[staging.example.com/public/wp-includes/class-wp-hook.php](http://staging.example.com/public/wp-includes/class-wp-hook.php)(324): listmonk_integration_page_callback()
> #2 /var/www/vhosts/[staging.example.com/public/wp-includes/class-wp-hook.php](http://staging.example.com/public/wp-includes/class-wp-hook.php)(348): WP_Hook->apply_filters()
> #3 /var/www/vhosts/[staging.example.com/public/wp-includes/plugin.php](http://staging.example.com/public/wp-includes/plugin.php)(517): WP_Hook->do_action()
> #4 /var/www/vhosts/[staging.example.com/public/wp-admin/admin.php](http://staging.example.com/public/wp-admin/admin.php)(259): do_action()
> #5 /var/www/vhosts/[staging.example.com/public/wp-admin/options-general.php](http://staging.example.com/public/wp-admin/options-general.php)(10): require_once('...')
> #6 {main}
>  thrown

Created a new issue for this error here: https://github.com/post-duif/integration-listmonk-wordpress-plugin/issues/23 

It's a bug related to you not having WooCommerce installed. I will fix it in the next release.

**Comment by post-duif** [comment] 2024-02-25 20:30
@timscha I fixed #23 for you in the latest release, 1.2.2. Perhaps you could try to play with it using WPForms and see if you like it? If it is doable and easy I will look into Contact form 7 support, but it would take some time (and I am just doing this in my free time :)).

**Comment by timscha** [comment] 2024-02-26 06:38
Hej @post-duif - Thanks for the fix. I can confirm the error is gone.
The problem with WPForms is, that it's not supported with my theme/causes some other problems.

But I appreciate your effort, but I guess I have to look around for another newsletter plugin than. :(

**Comment by post-duif** [comment] 2024-03-10 15:48
Hey @timscha! I worked a few hours extra and added Contact Form 7 support for you. :) Could you please let me know if it works for your use case?

The new release can be found here: https://github.com/post-duif/integration-listmonk-wordpress-plugin/releases/tag/v.1.3.0 

What you need for the integration to work is to 

1) enable Contact Forms 7
2) create a newsletter form with the fields "your-name" and "your-email" present. Those will be sent to listmonk.
3) add the shortcode for the form on any page you'd like and remember that page ID
3) enable the integration on the listmonk settings page
4) enter the page ID of the page where you entered the Contact Forms 7 shortcode

Then it should work! :) Would you please let me know if it works? 

(PR: https://github.com/post-duif/integration-listmonk-wordpress-plugin/pull/27)

**Comment by timscha** [comment] 2024-03-11 07:01
😱 Thank you @post-duif for doing that!!! I really appreciate that. I'll be on the road until tomorrow but I'll test it immediately once I am back. Thank you so much!!

**Comment by post-duif** [comment] 2024-03-11 14:46
> 😱 Thank you @post-duif for doing that!!! I really appreciate that. I'll be on the road until tomorrow but I'll test it immediately once I am back. Thank you so much!!

Thanks, I hope it works as intended! Please let me know :)

**Comment by timscha** [comment] 2024-03-14 15:14
Hi @post-duif - I finally had time to test it, without success unfortunately.
First I tried an existing form, afterwards I created a completly new.

I used the first list / didn't changed anything on these settings. Added the page id. Than I tried to add my email to the list but nothing happens in listmonk.

Also, I would love (I don't know if it's possible to use also multiple contact forms. For example I have a contact form on my contact page. Perfect scenario would be, that I just have to add a checkbox, if a user wants to receive newsletter.

**Comment by post-duif** [comment] 2024-03-14 15:26
@timscha quick initial comment: you need the WordPress page ID, not the Contact Form 7 list ID. I admit that's a hit confusing but that's how their code works.

So you would have to check the url of the WordPress page you're editing and inputting the CF7 shortxode to. The edit page url will contain something like page=58. That's what you have to input in the listmonk integration page.

**Comment by timscha** [comment] 2024-03-14 17:12
@post-duif I can confirm I tried the page id. The page link is: https://example.com/wp-admin/post.php?post=131708&action=edit

You can see, it's the same ID i used in my screenshot. Also, I used the code, provided from contact form.

[contact-form-7 id="bd07447" title="Newsletter"]

**Comment by post-duif** [comment] 2024-03-14 17:16
> @post-duif I can confirm I tried the page id. The page link is: https://example.com/wp-admin/post.php?post=131708&action=edit
> 
> You can see, it's the same ID i used in my screenshot. Also, I used the code, provided from contact form.
> 
> [contact-form-7 id="bd07447" title="Newsletter"]
> 
> 

Hmm, strange. No errors in the logs? And you did save the correct listmonk server url and password? 

Could you, just for sake of testing, try to use the WPForms integration? I know it doesn't work with your theme, but just for debugging.

**Comment by timscha** [comment] 2024-03-15 11:36
I tried it now with WPForms, even that didn't worked first. I had to re enter my listmonk details. After that it worked. But the contact form 7 integration still not works at all.

**Comment by post-duif** [comment] 2024-03-15 16:28
Glad it works with WPForms! :)

Any logs and errors you can share? Otherwise it's hard to debug; I don't experience any issues with CF7 in testing.

**Comment by timscha** [comment] 2024-03-15 18:34
@post-duif Unfornatly no. I only can confirm that the form itself is working, as I get a email.
My error logs of nginx stays silence.

**Comment by post-duif** [comment] 2024-03-15 18:42
I meant the WordPress logs, not nginx. Unfortunately I do not know what the problem could be now. And as I am developing this in my free time I will have to see if I have time to develop this further.

Have you tried it with different types of simpler CF7 forms? On different WordPress pages with a different page ID?

-------- Original Message --------

**Comment by post-duif** [comment] 2024-03-20 10:37
@timscha if you want me to work on debugging I do need some more info and testing from you. I have tested it with two different WordPress servers and the Contact Form 7 integration works flawlessly here. So unfortunately I do not know if there is an error with the plugin or something in your server settings / CF7 settings. Would love to fix it for you, but now I have nothing to go off on!

**Comment by timscha** [comment] 2024-03-22 06:28
Hi @post-duif - Sorry for the delayed response I wasn't at home for a couple for days.
I wish I could more information, but there aren't any. I turned the debug function in WordPress and also the debug log. But there no entries. The form itself is working as I receive the information which I enter during my test.

Is there maybe a compatible issue as I use PHP 8.3 or should the plugin be compatible with that? Just as an idea.

**Comment by post-duif** [comment] 2024-04-03 14:25
@timscha I don't think so, PHP 8.3 and WordPress 6.5 work fine for me.

Can you replace some code in the plugin file so we can debug? The only changes are I added some debug logging to the CF7 function.

In listmonk-integration.php, please change listmonk_send_data_through_contact_form_7 function with this:

function listmonk_send_data_through_contact_form_7( $contact_form, $abort, $submission ) {
    if (!listmonk_are_listmonk_settings_configured()) {
        return; // Abort if settings are not configured
    }
    $listmonk_cf7_form_id = absint(get_option('listmonk_cf7_form_id')); // convert form id from option to integer
    $listmonk_cf7_integration_on = sanitize_text_field(get_option('listmonk_cf7_integration_on')); // check if the listmonk form option is disabled in settings

    // check if the form id matches the form id from the settings page and if the listmonk form option is enabled
    if (get_option('listmonk_cf7_integration_on') != 'yes' || absint($contact_form->id()) !== $listmonk_cf7_form_id) { 
        error_log('CF7 integration not enabled or id doesnt match');
        error_log('Current page ID: ' . absint($contact_form->id()) .'');
        error_log('CF7 page ID from listmonk settings: ' . $listmonk_cf7_form_id . '');
        return;
    }

    $posted_data = $submission->get_posted_data();
    $ip = listmonk_get_the_user_ip(); // define ip address of user, used for listmonk consent recording

    // Retrieve specific field data
    $email = isset($posted_data['your-email']) ? sanitize_text_field($posted_data['your-email']) : '';
    $name = isset($posted_data['your-name']) ? sanitize_email($posted_data['your-name']) : '';
    error_log('Email: '  . $email. '');
    error_log('Name: '  . $email. '');

    // Add your logic here to send data to listmonk
    
    // retrieve data to send to listmonk
    $website_name = sanitize_text_field(get_bloginfo( 'name' )); // Retrieves the website's name from the WordPress database
    $listmonk_list_id = absint(get_option('listmonk_list_id', 0)); // get listmonk list id from settings page
    error_log('Listmonk list ID : '  . $listmonk_list_id . '');
    
    ## for listmonk
    $attributes = [
        'subscription_origin' => 'Contact Form 7',
        'confirmed_consent' => true, // user gave consent to receive newsletter
        'ip_address' => $ip, // ip address of user
        'consent_agreement' => 'I consent to receiving periodic newsletters from ' . $website_name . '.', // Use the website name dynamically
    ] ;

    // remove email from name field input
    $pattern = '/[^@\s]*@[^@\s]*\.[^@\s]*/'; // to avoid spam
    $replacement = '[removed]';

    // sanitize name input
    $name = sanitize_text_field(strip_tags($name)); // get name from form; this assumes it is the first field in the form
    $name_email_stripped = preg_replace($pattern, $replacement, $name); // remove email from name field input
    $name_stripped_all = preg_replace('/[a-zA-Z]*[:\/\/]*[A-Za-z0-9\-_]+\.+[A-Za-z0-9\.\/%&=\?\-_]+/i', $replacement, $name_email_stripped); // remove urls from name field input

    // body to send with POST to the API
    $body = array(
        'name'  => $name_stripped_all,
        'email' => $email,
        'status' => 'enabled',
        'lists' => [(int)$listmonk_list_id],
        'attribs' => $attributes,
        'preconfirm_subscriptions' => false, // set presubscription to false, because anyone can enter an email here
    ) ;

    #listmonk credentials
    $listmonk_url = esc_url_raw(get_option('listmonk_url'));
    $listmonk_username = sanitize_text_field(get_option('listmonk_username'));

    ## password decryption using the fsd-data-encryption class
    $encryption = new listmonk_FSD_Data_Encryption();
    $encrypted_password = sanitize_text_field(get_option('listmonk_password'));
    $listmonk_password = $encryption->decrypt($encrypted_password);
    
    // append the url from the settings page
    $url = $listmonk_url . '/api/subscribers';

    // using the send_data_to_listmonk function we defined earlier, we communicate with the listmonk API through WordPress HTTP API

    $response = listmonk_send_data_to_listmonk_wordpress_http_api($url, $body, $listmonk_username, $listmonk_password);

    // Optionally skip sending the email
    // add_filter('wpcf7_skip_mail', function() { return true; });

    return $contact_form;
}

After that, try to submit the form again and check the WP_DEBUG log. Please note you have to have WP Debugging enabled on your site (Google on how to do that).

Please share with me the debugging outcome, which could look something like this, if there is a mismatch between the page ID and the form ID:

[03-Apr-2024 14:10:23 UTC] CF7 integration not enabled or id doesnt match
[03-Apr-2024 14:10:23 UTC] Contact form id: 155
[03-Apr-2024 14:10:23 UTC] Form id from listmonk settings: 333

**Comment by post-duif** [comment] 2024-04-26 15:06
Any progress @timscha? Otherwise I will close this issue

**Comment by timscha** [comment] 2024-05-04 05:50
@post-duif Sorry for the long waiting, I was abroad again. But I have very good news, I got it working/I found what's going on thanks to the debug code.

First, I got this warning: 

[04-May-2024 05:37:00 UTC] CF7 integration not enabled or id doesnt match
[04-May-2024 05:37:00 UTC] Current page ID: 61541
[04-May-2024 05:37:00 UTC] CF7 page ID from listmonk settings: 88617

I double checked it. I made screenshot of the URL of the page where the contact form is placed in.
![CleanShot 2024-05-04 at 07 38 27@2x](https://github.com/post-duif/integration-listmonk-wordpress-plugin/assets/4650393/2d2880e9-161e-4b4c-9c45-9930da50f2df)

What I don't get, why and where the plugin get's the other ID from. Funny thing is, with the provided page id from the plugin it works. I am not able to see this id 61541 somewhere else. Do you have an idea for that?

Also, I assume that it is not possible to make an entry dependent on whether a check mark has been set or not?
With the current configuration, the entries are entered directly in Listmonk and even set as 
"confirmed_consent": true,
"consent_agreement": "I consent to receiving periodic newsletters from Tim.",

which is unfortunately a nightmare in terms of data protection, without sending a opt-in email from Listmonk. 😆

**Comment by timscha** [comment] 2024-05-04 06:27
And please let me know, where I can buy/send you a coffee as thank you for your help. :)

**Comment by post-duif** [comment] 2024-05-04 18:54
@timscha 

I'm really glad it worked out! 

Pretty strange the difference in page ID. I can't seem to reproduce it, perhaps something related to your theme? The expected behaviour should be that it matches the post ID, but I'm not sure why it doesn't happen in your case. Anyhow I'm glad it works now!

As for the double opt-in: 

`
'preconfirm_subscriptions' => false, // set presubscription to false, because anyone can enter an email here
`

This part of the code ensures that new subscriptions entered through CF7 forms are set to 'Unconfirmed' in listmonk automatically. Have you checked if that is the case in listmonk itself? And that the list you are sending data to is set to 'Double opt-in'? That should already solve the issue. 

In listmonk it should look like this:
<img width="495" alt="Screenshot 2024-05-04 at 20 50 02" src="https://github.com/post-duif/integration-listmonk-wordpress-plugin/assets/126626953/c55ff1ec-a66a-4429-aae0-9870b621e9de">

And I agree that this is confusing, as it was based on my own use case where I already had a consent checkbox present:

`
"confirmed_consent": true,
"consent_agreement": "I consent to receiving periodic newsletters from Tim.",
`

These are not variables used by listmonk but just for documentation purposes. I could try to make them dependent on a specific checkbox, but it would complicate things more and would take time to implement. What you could do for now is just create a checkbox that asks for consent, as the double opt-in doesn't depend on that but should work already.

As for the coffee, so kind, thank you! The link is https://buymeacoffee.com/postduif.

**Comment by timscha** [comment] 2024-05-05 06:32
@post-duif It isn't theme related, I checked it by switching to one of the wordpress default ones, without any change.
Is it possible that you can leave the debug code in the prod version/add a toggle maybe? So in case you are pushing an update via wordpress.org I am still be able to check it (if I have to change something). :)

Thanks for the advice with the Double opt-in, I'll use this now and the checkbox I will try it that way. 

Coffee is on the way. :)

**Comment by post-duif** [comment] 2024-05-08 18:10
I will close the issue for now and created two separate issues for your suggestions. Thanks!

**Closed by post-duif** 2024-05-08 18:10 UTC

**Comment by post-duif** [comment] 2024-08-06 10:04
Debug mode is added in v1.4.0: https://github.com/post-duif/integration-listmonk-wordpress-plugin/releases/tag/v1.4.0.
